/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Configuracion.Sistema;
import Entidades.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class AreaClientes extends javax.swing.JFrame {

    /** Creates new form AreaClientes */
    public AreaClientes() {
        initComponents();
        cargarTabla();
        editarCliente(false);
        
    }
    
    public void editarCliente(boolean estado){
        this.jTextFieldNombreSelect.setEditable(estado);
        this.jTextFieldDniSelect.setEditable(false);
        this.jTextFieldDireccionSelect.setEditable(estado);
        this.jTextFieldNroTelfSelect.setEditable(estado);
        this.jTextFieldUserIdeSelect.setEditable(estado);
        this.jButtonGuardarCambios.setEnabled(estado);
    }
    
    public void limpiarDatos(){
        this.jTextFieldNombreSelect.setText(null);
        this.jTextFieldDniSelect.setText(null);
        this.jTextFieldDireccionSelect.setText(null);
        this.jTextFieldNroTelfSelect.setText(null);
        this.jTextFieldUserIdeSelect.setText(null);
    }
    
    public void cargarTabla(){
        String[] titulos=Sistema.usuarios.getTitulosClientes();
        String[][] datos=Sistema.usuarios.getClientes();
        DefaultTableModel modelo= new DefaultTableModel(datos,titulos);
        this.jTClientes.setModel(modelo);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDniSelect = new javax.swing.JTextField();
        jTextFieldDireccionSelect = new javax.swing.JTextField();
        jTextFieldNroTelfSelect = new javax.swing.JTextField();
        jTextFieldNombreSelect = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUserIdeSelect = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonGuardarCambios = new javax.swing.JButton();
        jTextFielDniBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTClientes.setRowHeight(30);
        jTClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTClientes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTClientesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTClientes);
        if (jTClientes.getColumnModel().getColumnCount() > 0) {
            jTClientes.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            jTClientes.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            jTClientes.getColumnModel().getColumn(2).setHeaderValue("Title 3");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 290, 200));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonVolver4.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 30));

        jButton4.setText("Añadir Cliente");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 120, -1));

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonEliminar.png"))); // NOI18N
        jButtonEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("AREA CLIENTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));
        getContentPane().add(jTextFieldDniSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 120, -1));
        getContentPane().add(jTextFieldDireccionSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 120, -1));
        getContentPane().add(jTextFieldNroTelfSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 120, -1));
        getContentPane().add(jTextFieldNombreSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 120, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Dni");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Nro telefonico");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));
        getContentPane().add(jTextFieldUserIdeSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 120, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("User_Ide");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 130, -1));

        jButtonGuardarCambios.setText("Guardar Cambios");
        jButtonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        jTextFielDniBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFielDniBuscarMouseClicked(evt);
            }
        });
        jTextFielDniBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielDniBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFielDniBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 204, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, -1, 40));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonCerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setBorderPainted(false);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo4.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InicioAdministrador i= new InicioAdministrador();
        i.setVisible(true);
        i.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTClientesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTClientesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTClientesAncestorAdded

    private void jTextFielDniBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielDniBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielDniBuscarActionPerformed

    private void jTextFielDniBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFielDniBuscarMouseClicked
        //
    }//GEN-LAST:event_jTextFielDniBuscarMouseClicked

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        Usuario user;
        user=Sistema.usuarios.getUsuario(this.jTextFielDniBuscar.getText());
        if(user!=null&&user instanceof Cliente){
            this.jTextFieldNombreSelect.setText(user.getNombre());
            this.jTextFieldDniSelect.setText(user.getDni());
            this.jTextFieldUserIdeSelect.setText(user.getId_user());
        }else{
            JOptionPane.showMessageDialog(null, "No se ha encontrado cliente");
        }
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        Icon imagen = new ImageIcon(getClass().getResource("/Recursos/BotonEliminar.png"));
        String[] opciones = {"Sí","Cancelar"};
        
        int i = JOptionPane.showInternalOptionDialog(null, "¿Está seguro que desea ELIMINAR este CLIENTE de forma PERMANENTE?",
                "Elija una opción", WIDTH, HEIGHT, imagen, opciones, EXIT_ON_CLOSE);
        if(i==0){
            if(Sistema.usuarios.eliminarUsuario(this.jTextFieldDniSelect.getText())){
                JOptionPane.showMessageDialog(null, "Eliminado");
                this.cargarTabla();
                limpiarDatos();
                editarCliente(false);
            }else{
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientesMouseClicked
        int seleccionar = jTClientes.rowAtPoint(evt.getPoint());
        this.jTextFieldDniSelect.setText(String.valueOf(this.jTClientes.getValueAt(seleccionar,0 )));
        this.jTextFieldNombreSelect.setText(String.valueOf(this.jTClientes.getValueAt(seleccionar,1 )));
        this.jTextFieldUserIdeSelect.setText(String.valueOf(this.jTClientes.getValueAt(seleccionar, 2)));
    }//GEN-LAST:event_jTClientesMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Sistema.usuarios.buscar(this.jTextFieldDniSelect.getText())){
            editarCliente(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosActionPerformed
        Cliente clienteActual = (Cliente) Sistema.usuarios.getUsuario(this.jTextFieldDniSelect.getText());
        Cliente clienteMod = new Cliente(this.jTextFieldNombreSelect.getText(),
                this.jTextFieldDniSelect.getText() , this.jTextFieldUserIdeSelect.getText(), clienteActual.getPassword());
        if(Sistema.usuarios.modificarUsuario(clienteActual.getDni(), clienteMod)){
            JOptionPane.showMessageDialog(null,"Modificado");
            cargarTabla();
            editarCliente(false);
        }else{
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButtonGuardarCambiosActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardarCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTClientes;
    private javax.swing.JTextField jTextFielDniBuscar;
    private javax.swing.JTextField jTextFieldDireccionSelect;
    private javax.swing.JTextField jTextFieldDniSelect;
    private javax.swing.JTextField jTextFieldNombreSelect;
    private javax.swing.JTextField jTextFieldNroTelfSelect;
    private javax.swing.JTextField jTextFieldUserIdeSelect;
    // End of variables declaration//GEN-END:variables

}
